'use strict';
const pieces={cup:{name:'青釉杯',glaze:'青釉',poem:'把時間，握在手裡。',type:'日用杯',texture:'青藍釉面與素土底足',use:'一口茶，一段留給自己的時間。',description:'從深藍到霧白的釉色，讓一件小器物也有自己的風景。圓潤器形與素土底足，是這份日常工藝想像的起點。',alt:'原創青釉杯概念：斑駁藍色釉面與素土底足',image:'cup.webp'},dish:{name:'霧白淺盤',glaze:'霧白',poem:'把一束光，盛進日常。',type:'淺盤',texture:'柔白釉面與環形拉坯紋路',use:'留一點空間，讓一餐慢慢展開。',description:'淺淺的器形，不把視線拉走。柔和白釉與一圈圈紋路，讓食物、光線與桌面各有自己的位置。',alt:'原創霧白淺盤概念：柔和白釉與環形拉坯紋理',image:'dish.webp'},vase:{name:'土色花器',glaze:'土色',poem:'留一個空位，給今天的花。',type:'細口花器',texture:'深棕釉色與直向起伏紋理',use:'一枝花，也能改變桌上的風景。',description:'向上收束的器形與直向紋理，讓光在不同角度留下變化。不插花的時候，也能保留一份安靜的存在。',alt:'原創土色花器概念：修長器形與深棕色直向紋理',image:'vase.webp'}};
const chosen=new Set();let current='cup',returnFocus=null,dialogMode='detail',returnToTray=false;const dialog=document.querySelector('#object-dialog'),content=document.querySelector('#dialog-content');
const status=text=>document.querySelector('#action-status').textContent=text;
const count=()=>document.querySelector('#tray-count').textContent=String(chosen.size);
function showDialog(mode){if(!dialog.open){returnFocus=document.activeElement;dialog.showModal();}document.querySelector('#dialog-context').textContent=mode;}
function openPiece(id){const p=pieces[id];if(!p)return;if(!dialog.open)returnToTray=false;else if(dialogMode==='tray')returnToTray=true;dialogMode='detail';content.replaceChildren();const img=document.createElement('img');img.className='detail-image';img.src='assets/'+p.image;img.alt=p.alt;img.width=1536;img.height=1024;const title=document.createElement('h2');title.id='dialog-title';title.className='detail-heading';title.textContent=p.name;const desc=document.createElement('p');desc.className='detail-copy';desc.textContent=p.description;const dl=document.createElement('dl');dl.className='detail-dl';for(const[label,value]of[['器形',p.type],['紋理',p.texture],['日常',p.use]]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);dl.append(row);}const save=document.createElement('button');save.type='button';save.className='save-action';save.dataset.save=id;save.textContent=chosen.has(id)?'從我的選物移除':'加入我的選物';save.setAttribute('aria-pressed',String(chosen.has(id)));const note=document.createElement('p');note.className='dialog-note';note.textContent='原創器物概念。選物只保留在本頁，重新載入即清空。';const browse=document.createElement('div');browse.className='browse-actions';const ids=Object.keys(pieces),i=ids.indexOf(id);for(const[step,label]of[[-1,'上一件器物'],[1,'下一件器物']]){const b=document.createElement('button');b.type='button';b.dataset.detail=ids[(i+step+ids.length)%ids.length];b.textContent=label;browse.append(b);}content.append(img,browse,title,desc,dl,save,note);if(returnToTray){const back=document.createElement('button');back.type='button';back.className='dialog-back';back.dataset.back='';back.textContent='返回我的選物';content.append(back);}showDialog('器物細節');document.querySelector('#close-dialog').focus();}
function openTray(){dialogMode='tray';returnToTray=false;content.replaceChildren();const title=document.createElement('h2');title.id='dialog-title';title.className='detail-heading';title.textContent='我的選物';content.append(title);if(!chosen.size){const wrap=document.createElement('div');wrap.className='empty-tray';const p=document.createElement('p');p.textContent='還沒有選物。先從器形與釉色，找一件與你合拍的器物。';const b=document.createElement('button');b.type='button';b.className='save-action';b.dataset.close='';b.textContent='繼續探索器物';wrap.append(p,b);content.append(wrap);}else{const list=document.createElement('div');list.className='saved-list';for(const id of chosen){const p=pieces[id],row=document.createElement('article'),img=document.createElement('img'),body=document.createElement('div'),h=document.createElement('h3'),actions=document.createElement('div');row.className='saved-row';img.src='assets/'+p.image;img.alt=p.alt;img.width=84;img.height=70;h.textContent=p.name;actions.className='saved-actions';for(const[action,label]of[['detail','查看細節'],['remove','移除選物']]){const b=document.createElement('button');b.type='button';b.dataset[action]=id;b.textContent=label;actions.append(b);}body.append(h,actions);row.append(img,body);list.append(row);}content.append(list);const note=document.createElement('p');note.className='dialog-note';note.textContent='這是你的靈感清單，不是訂單。選物不會傳送或永久儲存。';content.append(note);}showDialog('選物清單');document.querySelector('#close-dialog').focus();}
function closeDialog(){dialog.close();}
document.querySelector('#close-dialog').addEventListener('click',closeDialog);dialog.addEventListener('close',()=>{returnFocus?.focus();returnFocus=null;returnToTray=false;});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
document.querySelector('#open-tray').addEventListener('click',openTray);document.querySelector('#stage-detail').addEventListener('click',()=>openPiece(current));
document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.stage;const p=pieces[current];document.querySelector('#stage-image').src='assets/'+p.image;document.querySelector('#stage-image').alt=p.alt;document.querySelector('#stage-name').textContent=p.glaze;document.querySelector('#stage-poem').textContent=p.poem;document.querySelectorAll('[data-stage]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));status('展台切換為'+p.name);}));
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let visible=0;document.querySelectorAll('[data-kind]').forEach(x=>{x.hidden=b.dataset.filter!=='all'&&x.dataset.kind!==b.dataset.filter;if(!x.hidden)visible++;});document.querySelector('#filter-status').textContent='顯示'+visible+'件器物';}));
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.detail)openPiece(b.dataset.detail);if(b.hasAttribute('data-close'))closeDialog();if(b.hasAttribute('data-back'))openTray();if(b.hasAttribute('data-open-tray'))openTray();if(b.dataset.save){const id=b.dataset.save;if(chosen.has(id)){chosen.delete(id);status('已移除'+pieces[id].name);}else{chosen.add(id);status('已加入'+pieces[id].name);}count();b.textContent=chosen.has(id)?'從我的選物移除':'加入我的選物';b.setAttribute('aria-pressed',String(chosen.has(id)));}if(b.dataset.remove){chosen.delete(b.dataset.remove);count();status('已移除'+pieces[b.dataset.remove].name);openTray();}});
// Keep keyboard focus inside the active sheet, including the boundary between the last and first control.
dialog.addEventListener('keydown',event=>{if(event.key!=='Tab')return;const controls=[...dialog.querySelectorAll('button,a[href]')].filter(x=>!x.disabled&&x.getClientRects().length);if(!controls.length)return;const first=controls[0],last=controls.at(-1),active=document.activeElement;if(event.shiftKey&&(active===first||!dialog.contains(active))){event.preventDefault();last.focus();}else if(!event.shiftKey&&(active===last||!dialog.contains(active))){event.preventDefault();first.focus();}});
